# Generated by Django 5.1.6 on 2025-03-13 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_rename_user_comment_author_rename_user_like_author_and_more'),
        ('posts', '0004_blogpost_excerpt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
