# Generated by Django 5.1.6 on 2025-03-06 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Public', models.CharField(choices=[('None', 'None'), ('Read', 'Read'), ('Read and Edit', 'Read and Edit')], default='Read', max_length=15)),
                ('Authenticated', models.CharField(choices=[('None', 'None'), ('Read', 'Read'), ('Read and Edit', 'Read and Edit')], default='Read', max_length=15)),
                ('Team', models.CharField(choices=[('None', 'None'), ('Read', 'Read'), ('Read and Edit', 'Read and Edit')], default='Read', max_length=15)),
                ('Author', models.CharField(default='Read and edit', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
