# Generated by Django 5.1.6 on 2025-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_authenticated_blogpost_authenticated_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_access',
            field=models.CharField(choices=[('Read and Edit', 'Read and Edit')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='public_access',
            field=models.CharField(choices=[('None', 'None'), ('Read', 'Read')], max_length=15),
        ),
    ]
