# Generated by Django 5.1.6 on 2025-03-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_blogpost_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
    ]
